### PR TITLE
Wns fast

### PR DESCRIPTION
**Pull request by sextonw**

### CODE REVIEW

**Comment by larsvilhuber** [comment]
@sextonw @wns32 : Could you adjust the pull request to use directory programs/ not newprograms/ ? this replaces the existing programs, not adds new programs. I can't do that during the pull request.

**Comment by sextonw** [comment]
@larsvilhuber Yes, I'll take care of that.

**Comment by larsvilhuber** [comment]
The old code is available either as branch "oldcode" or as release https://github.com/labordynamicsinstitute/SynUSpopulation/tree/v201703-beta if needed.

[https://avatars3.githubusercontent.com/u/8550306?s=400&v=4]<https://github.com/labordynamicsinstitute/SynUSpopulation/tree/v201703-beta>

labordynamicsinstitute/SynUSpopulation<https://github.com/labordynamicsinstitute/SynUSpopulation/tree/v201703-beta>
github.com
SynUSpopulation - Creating a synthetic US population dataset




--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by sextonw** [comment]
Ok. I think c29103f should do it. I'll update the readme soon to reflect the major differences in versions. The 2 main ones though are: 1) Recode of race vars was removed because it didn't meet the needs our collaborators. We may revisit this in the future but the recodes were only added for a specific use case that is no longer revelant because the race codes are changing on the 2020 census. 2) The 'id' var values have changed though the variable still serves the same purpose. It uniquely identifies replicated individuals with replicated households. Household 'ids' now have the form _serialno_._replicationno_ This change was necessary to facilitate a significant restructuring of the code. The big difference now is that rep_syn_housing and rep_syn_person can now be run simultaneously. Each now take about 3 hours to complete putting the total runtime of all programs around 3.5 hrs.

**Comment by sextonw** [comment]
I'm going offline now.

**Comment by larsvilhuber** [comment]
Thanks.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by larsvilhuber** [comment]
Looks good to me. The comments address all my questions. Updates to the README coming.

**Review by larsvilhuber — APPROVED** [review]
Comments by @sextonw and @wns32 address all my questions.

**Comment by larsvilhuber** [comment]
@sextonw : when you have time, delete the branch wns-fast.

**Pull request merged**
